### ISSUE TITLE
Increase coverage

### ISSUE THREAD

**Issue by kkweon** [dl4ab/timebot#11]
The coverage dropped to [![Coverage Status](https://coveralls.io/repos/github/dl4b/timebot/badge.svg)](https://coveralls.io/github/dl4b/timebot)
 since #10 

Need to maintain 90%+ coverage

**Comment by nicewook** [comment]
오오오... 감사합니다. 
travis 에서 제공하는 건가보죠? 검증할 수 있는 테스트 코드를 작성해야는 것이구요.

**Comment by kkweon** [comment]
다 자동은 아니고travis는 실행 주체 이고 coveralls.io 의 서비스입니다.

travis 는 테스트용 컴퓨터를 빌려주는 서비스라고 생각하시면 됩니다.
그래서 실행 스크립트를 설정할 수 있는데 거기서 coveralls로 보내는 스크립트가 추가 되있습니다.

https://github.com/dl4b/timebot/blob/master/.travis.yml#L18
