### ISSUE TITLE
내용에 시간이 표시되면 자동으로 반응하기

### ISSUE THREAD

**Issue by kkweon** [dl4ab/timebot#18]
유저1: 이번 미팅은 2019-01-04 21:51 KST 에 하겠습니다
봇: 2019-01-04 04:51 PST (가능하면 쓰레드로 담)

유저1: ㄴㅇ이ㄱ자ㅂㄴㅇㅣㅇㅂ자ㅇㄴㅇㅣㅂ자 2019-01-04 21:52 PST
봇: 2019-01-05 14:51 KST

**Comment by nicewook** [comment]
언뜻 봤는데 이거 이야기로 보임
http://slackapi.github.io/hubot-slack/basic_usage

**Comment by nicewook** [comment]
현시점 타임봇에게 입력해주면 Time is fly 라고 회신이 옵니다.

**Comment by kkweon** [comment]
왜 그렇죠 :thinking: ? 로컬브랜치 deploy하셨나요?
마스터로 PR해주시겠어요?

**Comment by kkweon** [comment]
왜 회신이 오는지 모르겠네요 event api도 enabled안되있는데 :sob:

**Comment by kkweon** [comment]
현재 https://github.com/dl4ab/timebot/tree/task/20190108/add-event-api 브랜치에서 작업중인게 있습니다.
곧 PR 올리겠습니다

**Comment by nicewook** [comment]
아하~ 휴봇이 deprecate 된거도 있고, 슬랙자체도 뭔가 있을거 같았습니다. 
즐겁게 기다리겠습니다. :)
